### PR TITLE
API upgrade required

### PR DESCRIPTION
**Pull request by gamerlv**
API 1.0 has been deprecated for a while and has been terminated on jun 11 2013. 
This spark no longer works due to this.

https://dev.twitter.com/blog/api-v1-is-retired

A possible solution is application only authentication:
https://dev.twitter.com/docs/auth/application-only-auth

### CODE REVIEW

**Comment by cnccld** [comment]
Waiting for the fix :)

**Comment by gamerlv** [comment]
@joeauty Could do, have 'fixed' it. But used plain curl and not the rest or cUrl library. Any problem with that?

**Comment by joeauty** [comment]
None! Whatever works... I was just using those other Sparks because this Spark was a derivative of another one that required these additional Sparks. I'm happy to incorporate your changes, and of course I will give you full credit and will be sure to express ample gratitude and appreciation :)

**Comment by hjujah** [comment]
Looking forward to the solution of this problem...

**Comment by joeauty** [comment]
I'm working on this as we speak, but the curl call in getAuthCode() is currently not returning any output. Were you able to get this to work, gamerlv?

**Comment by joeauty** [comment]
Hey guys,

I've gotten this working. If you wouldn't mind, can you please try the latest code in this repository to confirm that things are working? Gamerlv, I have no idea how you got things working (if you did at all) without the oAuth access key and access key secret. See the updated readme for instructions how to access these values

**Comment by gamerlv** [comment]
I did get it to work, ran it multiple times. The `getAuthCode()` returns a (maybe cached) bare token that can be used with a application only request. This is a subset of the oauth authentication method that will only allow reading  of tweets. An access token isn't required for that.  

The code I provided is running live on my own site so I know it works, but since you went full oauth I can't help any further since I find that way more trouble than it's worth.

**Comment by joeauty** [comment]
Ahh, I figured that based on this (https://dev.twitter.com/docs/api/1.1/get/statuses/user_timeline) mentioning that authentication is required, that this referred to full oAuth, which I know is particularly nasty, particularly the outdated 1.0 spec Twitter is still using. If we can figure out how to get your method to work I'm game, but it was generating an error code 89, and according to this page: https://dev.twitter.com/discussions/15626 this is because of the missing oAuth identifiers. After reading this page I decided to go down the oAuth path.

**Comment by gamerlv** [comment]
Did you update your dependencies? the method `http_header` isn't available in restclient < 2.1.0 and will fail silently. That's why I updated the spark.info

**Comment by joeauty** [comment]
I may have missed that. I'll try this out today and will let you know.

I'm kind of curious as to how you figured out that you don't need the oAuth keys for authorization/authentication... I don't disbelieve you at all, I'm just asking so that I can educate myself further :)

Thanks, I appreciate your help here!

**Comment by joeauty** [comment]
gamerlv: as it turns out I was using restclient 2.1.0 but I had another problem with a namespace conflict. I've sorted this out now, but I'm now getting "not authorized" errors. I think I'm going to go ahead with my version of the Spark, but I'm happy to continue working on this to simplify things if you are interested in working with me, but for now I'd just like to get something out there that I've gotten to work.

**Pull request merged**
